// FAKE DATA
export const books = [
  {
    id: 1,
    title: "You Become What You Think",
    url: "https://m.media-amazon.com/images/I/41lJNXRfFdL._SY445_SX342_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "The Power of Now",
    url: "https://m.media-amazon.com/images/I/4196LMdWilL._SY445_SX342_.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Becoming Supernatural",
    url: "https://m.media-amazon.com/images/I/41HHGZRXX4L._SY445_SX342_.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Inward",
    url: "https://m.media-amazon.com/images/I/81kz8apODnL._SL1500_.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The Active Side of Infinity",
    url: "https://m.media-amazon.com/images/I/51QegfNd3dL._SY445_SX342_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Tao Te Ching",
    url: "https://m.media-amazon.com/images/I/31nugar8YoL._SY445_SX342_.jpg",
    originalPrice: 70,
    salePrice: 12,
    rating: 5,
  },
  {
    id: 7,
    title: "The Body Keeps Score",
    url: "https://m.media-amazon.com/images/I/41gOE+HnOfL._SY445_SX342_.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "BREATH",
    url: "https://m.media-amazon.com/images/I/71gxuHqAF-L._SL1500_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Breaking the Habit of Being Yourself",
    url: "https://m.media-amazon.com/images/I/41Gdi8HJOmL._SY445_SX342_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "The Secret",
    url: "https://m.media-amazon.com/images/I/51m8T+C5NfL._SX342_SY445_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "Reality is Not What It Seems",
    url: "https://m.media-amazon.com/images/I/51afFxAcmBL._SY445_SX342_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Signs",
    url: "https://m.media-amazon.com/images/I/41R6Kh+GnSL._SY445_SX342_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];